---

  - hosts: all
    become: true
    tasks:

      - name: Checking update_cashe RHEL9
        tags: always
        yum:
          update_only: yes
          update_cache: yes

      - name: start httpd (RHEL9)
        ansible.builtin.service:
          name: httpd
          state: started

      - name: Update firewall setting for port 80
        ansible.posix.firewalld:
          port: 80/tcp
          permanent: true
          state: enabled
